spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application: 
    name: microcloud-config-eureka-client
server:
  port: 7001
security:
  basic:
    enabled: true   # 启用安全认证处理
  user:
    name: edmindev     # 用户名
    password: 123  # 密码
eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmindev:123@eureka-7001.com:7001/eureka
   #在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，为了防止程序报错，所以我们需要禁用它的客户端注册行为
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7001.com # 定义Eureka实例所在的主机名称
---
spring:
  profiles: beta
  application: 
    name: microcloud-config-eureka-client
server:
  port: 7001
security:
  basic:
    enabled: true   # 启用安全认证处理
  user:
    name: edminbeta     # 用户名
    password: 123  # 密码
eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edminbeta:123@eureka-7001.com:7001/eureka
  #在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，为了防止程序报错，所以我们需要禁用它的客户端注册行为
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7001.com # 定义Eureka实例所在的主机名称
