spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microcloud-config-client
eureka:
  client:
    service-url:
      # defaultZone: http://edmin:123@eureka-dev.com:7001/eureka
      defaultZone: http://edmin:123@eureka-config.com:7301/eureka    # 此处一定要配置一个可以正常访问的defaultZone URL地址

info:
  app.name: msdn-microcloud-dev-1
  company.name: www.msdn.com
  app.version: v-dev-1.0.0

---
server:
  port: 8102
spring:
  profiles: beta
  application:
    name: microcloud-config-client
eureka:
  client:
    service-url:
      # defaultZone: http://edmin:123@eureka-beta.com:7001/eureka
      defaultZone: http://edmin:123@eureka-config.com:7301/eureka    # 此处一定要配置一个可以正常访问的defaultZone URL地址

info:
  app.name: msdn-microcloud-beta-2
  company.name: www.msdnjava.com
  app.version: v-beta-2.1.2