spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: 
    name: microcloud-config-client
eureka: 
  client:
    service-url:
      # defaultZone: http://edmin:123@eureka-dev.com:7001/eureka
      defaultZone: http://edmin:123@eureka-config.com:7301/eureka 	# 此处一定要配置一个可以正常访问的defaultZone URL地址
---
server:
  port: 8102
spring:
  profiles: beta
  application: 
    name: microcloud-config-client
eureka: 
  client:
    service-url:
      # defaultZone: http://edmin:123@eureka-beta.com:7001/eureka
      defaultZone: http://edmin:123@eureka-config.com:7301/eureka 	# 此处一定要配置一个可以正常访问的defaultZone URL地址